#!/usr/bin/env python3
import sys


def solve(N: int, d: "List[int]"):
    mx = sum(d)
    mn = 2 * max(d) - mx if max(d)>mx/2 else 0
    print(mx)
    print(mn)
    return


# Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    d = [int(next(tokens)) for _ in range(N - 1 - 0 + 1)]  # type: "List[int]"
    solve(N, d)

if __name__ == '__main__':
    main()
