#!/usr/bin/env python3
import sys

# Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def solve(N, C):
    N = int(N)
    C = [int(c) for c in C.rstrip()]
    # Failed to predict input format

    ans = [C.count(n) for n in [1,2,3,4]]

    print(max(ans), min(ans))

def main():
    def iterate_tokens():
        for line in sys.stdin:
            yield line

    tokens = iterate_tokens()
    N = next(tokens)  # type: str
    C = next(tokens)  # type: str
    solve(N, C)


if __name__ == '__main__':
    main()
