#!/usr/bin/env python3
import sys
import re

def solve(N: int, w: "List[str]"):
    name = 'takahashikun'
    w = ' '.join(w).lower()[:-1].split()
    count = w.count(name)
    print(count)

    return


# Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    w = [next(tokens) for _ in range(N - 1 - 0 + 1)]  # type: "List[str]"
    solve(N, w)

if __name__ == '__main__':
    main()
