#!/usr/bin/env python3
import sys

YES = "YES"  # type: str
NO = "NO"  # type: str


def solve(y: int):
    R1 = True if y % 4 == 0 else False
    R2 = True if y % 100 == 0 else False
    R3 = True if y % 400 == 0 else False
    R4 = not any([R1, R2, R3])

    if R4:
        print(NO)
    elif R3:
        print(YES)
    elif R2:
        print(NO)
    elif R1:
        print(YES)
    return


# Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    Y = int(next(tokens))  # type: int
    solve(Y)

if __name__ == '__main__':
    main()
