#!/usr/bin/env python3
import sys
import numpy as np

def solve(A: int, B: int, count = 0):
    if A == B:
        return count

    diff = A - B
    L = np.asarray([10, 5, 1, -1, -5, -10])

    mn = L[np.argmin(np.abs(L - diff))]

    return solve(A - mn, B, count+1)


# Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    A = int(next(tokens))  # type: int
    B = int(next(tokens))  # type: int
    print(solve(A, B))

if __name__ == '__main__':
    main()
