#!/usr/bin/env python3


# Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)

def main():
    
    N = int(input())
    A = list(map(int, input().split()))

    OK = True

    for a in A:
        if a % 2 == 0:
            if a % 3 == 0 or a % 5 == 0:
                pass
            else:
                OK=False
    if OK:
        print('APPROVED')
    else:
        print('DENIED')

if __name__ == '__main__':
    main()
