#!/usr/bin/env python3
import datetime

def is_divisible(Y,M,D):
    return True if Y % (M*D) == 0 else False

def solve(s):
    Y,M,D = list(map(int, s.split('/')))

    while not is_divisible(Y, M, D):
        next_day = datetime.date(Y, M, D) + datetime.timedelta(days=1)
        Y = next_day.year
        M = next_day.month
        D = next_day.day

    print('{}/{:02d}/{:02d}'.format(Y,M,D))


# Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    s = input()
    solve(s)
    # Failed to predict input format
    pass

if __name__ == '__main__':
    main()
